### ISSUE TITLE
Add Ubuntu 19.04 to supported ISO's

### ISSUE THREAD

**Issue by jamieede123** [kenorb-contrib/isorespin#8]
At the moment you cannot respin 19.04 ISO's

Add the checks related to 19.04 so the latest Ubuntu can be used

**Comment by jamieede123** [comment]
This can be fixed with https://github.com/kenorb-contrib/isorespin/issues/9

**Comment by bnku** [comment]
PR https://github.com/kenorb-contrib/isorespin/pull/10
